version: '3.7'
services:

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: always
    stdin_open: true
    tty: true        
    environment:
      - API_URL=http://localhost:3000/api/v1
      - MAX_CITY_ID=48356
    ports:
      - 80:3000
    volumes:
      - ./frontend:/app

  backend:
    build: ./backend
    restart: always
    command: start:dev
    depends_on:
      - mysql
    environment:
      - PORT=3000
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=myPassword
      - MYSQL_DATABASE=world
    ports:
      - 3000:3000
    volumes:
      - ./backend:/usr/src/app
    
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      - MYSQL_DATABASE=world
      - MYSQL_ROOT_PASSWORD=myPassword
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/tmp:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - 8081:80
