version: '3.7'
services:

  frontend:
    image: eji4h/docker-workshop-frontend:1.0.0
    restart: always
    environment:
      - API_URL=http://localhost:3000/api/v1
      - MAX_CITY_ID=48356
    ports:
      - 80:80
    networks: 
      - frontend

  backend:
    image: eji4h/docker-workshop-backend:1.0.2
    restart: always
    depends_on:
      - mysql
    environment:
      - PORT=3000
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=myPassword
      - MYSQL_DATABASE=world
    ports:
      - 3000:3000
    networks: 
      - backend
    
  mysql:
    image: mysql:5.6
    restart: always
    environment:
      - MYSQL_DATABASE=world
      - MYSQL_ROOT_PASSWORD=myPassword
    volumes:
      - db-data-prod:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    networks: 
      - backend

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - mysql
    links:
      - mysql:db
    ports:
      - 8080:80
    networks: 
      - backend

volumes:
  db-data-prod:

networks:
  frontend:
  backend:
