name: Build & Deploy

on:
  push:
    tags:
      - '**'

permissions:
  id-token: write
  contents: read

jobs:
  build-image:
    runs-on: ubuntu-22.04
    env: 
      build-platforms: linux/arm64
      docker-image: jitrak/ci-cd-demo
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ env.build-platforms }}
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./ci-cd-demo
          platforms: ${{ env.build-platforms }}
          push: true
          tags: ${{ env.docker-image }}:${{github.ref_name}}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-22.04
    needs: build-image
    steps:
      - uses: google-github-actions/auth@v1
        with:
          workload_identity_provider: projects/919110775509/locations/global/workloadIdentityPools/gha-pool/providers/gha-provider
          service_account: gha-service-account@born-to-dev-docker.iam.gserviceaccount.com

      - id: deploy
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: ci-cd-demo
          image: jitrak/ci-cd-demo:${{github.ref_name}}
          region: asia-southeast1

      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'